### ISSUE TITLE
Javascript errors in the Web dialog when downloading a model

### ISSUE THREAD

**Issue by ghost** [tav/wikihouse-plugin#1]
I get constant errors when trying to download a model using the plugin.

SU version 8.

**Comment by mintras** [comment]
I also do on the two installs I have made, and my friend has the same problem. Another friend just looked at the site and said this project seems dead, I am sure it is not, I am not a fluent coder or I would try and fix this.

Shame

**Comment by jbacus** [comment]
Not entirely clear what's causing these errors yet, but it is possible it has something to do with the way the wikihouse.cc website is structured. I think we can fix it, but the fix might not be in the plugin.

**Comment by tav** [comment]
@jbacus Thanks for looking into it — please do let us know what the issue is once you've found it...

**Comment by marc007** [comment]
![image](https://f.cloud.github.com/assets/229745/1825563/421a9ed6-71c3-11e3-8a1d-5109243424d5.png)

Same Javascript error on loading the Plugins "Get Model" function.

Hope that help,

Marc
